name: Deploy-App-spirit

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
      - uses: actions/checkout@v2

      # build the docker image and give it the name main
      - name: Build image
        run: docker build -t main .
      # run the docker image supply the secrets from the github secrets store.
      - name: execute
        run: >
          docker run
    #  main
    steps:
      - name: Checkout code
      - uses: actions/checkout@main
      # push changes
      - name: push changes to remote
        run: |
          git config --global user.name ${{ secrets.GH_USER }}
          git config --global user.email ${{ secrets.GH_MAIL }}

          git add docs
          git commit -m "GitHub Action: Build Book"
          git push
